# Generated by Django 3.2.7 on 2021-09-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Запись в таблице', 'verbose_name_plural': 'Записи в таблице'},
        ),
        migrations.AlterModelTable(
            name='table',
            table='single_page',
        ),
    ]
